<div class="test">
 <?php 
 $objectManager =  \Magento\Framework\App\ObjectManager::getInstance();        
 $storeManager  = $objectManager->get('\Magento\Store\Model\StoreManagerInterface');
 $storeID       = $storeManager->getStore()->getStoreId(); 
  $post = $block->getI();
  foreach($post as $item)
  {
    if($item->getStoreId()== $storeID)
    echo "<img class='fotorama__img' src='".$block->getBaseUrl()."pub/media/aht/image/upload/".$item->getImage()."' alt=''>";
  }
  ?>
 </div>


